### PR TITLE
Updating Copyright to 2015 and composer.phar

### PR DESCRIPTION
**Pull request by Lansoweb**

### CODE REVIEW

**Comment by Ocramius** [comment]
@Lansoweb can you avoid upgrading `composer.phar`? That is really something only the CR team should do (due to security issues)

**Comment by Lansoweb** [comment]
@Ocramius  Sure! Will revert it. Sorry :-)

**Comment by Lansoweb** [comment]
@Ocramius Reverted.

**Comment by Ocramius** [comment]
@Lansoweb thanks!

**Pull request merged**
