### PR TITLE
default http response code is 500, so fatal errors return correct res…

### PR DESCRIPTION
**Pull request by prolic**
…ponse code

### CODE REVIEW

**Comment by samsonasik** [comment]
👍

**Comment by Maks3w** [comment]
This only happens when you have XDebug enabled.

**Comment by prolic** [comment]
@Maks3w nope.

Try putting this in your index.php

```
<?php

throw new Exception('foo');
```

Disable xdebug and hit the browser, you'll see the exception and a http status code 200.

**Comment by Maks3w** [comment]
Declined by consistency with https://github.com/zfcampus/zf-apigility-skeleton/pull/83

**Pull request closed without merging**
