### PR TITLE
Add Vagrant recipe, update main `README.md` and update `.gitignore`

### PR DESCRIPTION
**Pull request by jeremiahsmall**
Bring over the Vagrant recipe from the Apigility skeleton app, and add some instructions to README

### CODE REVIEW

**Comment by gianarb** [comment]
PhPuppet generate unmaintainable code..
500 new files to provide webservice? We have remove this type of improvement from `zf.modules`
https://github.com/zendframework/modules.zendframework.com/pull/490

Sorry bot in my opinion this improvement is a bad idea :)   
Vagrant + PHP require a few considerations to resolve performance problems I don't know if this code apply them..

**Comment by jeremiahsmall** [comment]
I agree this is a clunky vagrant recipe. I prefer a customized box that doesn't require so much provisioning.

**Comment by jeremiahsmall** [comment]
NB, this recipe is copied exactly from the apigility skeleton app. I proposed it for consistency.

**Comment by gianarb** [comment]
We can try to send a PR to remove box from apigility.. :P for consistency :+1: :dancer:

**Comment by akrabat** [comment]
I'd like to see a simple, basic vagrant setup provided, with say a Vagrantfile and a simple shell script provisioner. Anyone who knows Vagrant well will have their own preferred provisioning system anyway.

**Comment by gianarb** [comment]
I agree with you @akrabat ...  
I don't understand community's idea about this.. :)

**Comment by akrabat** [comment]
Closing. If we're putting vagrant in, we're doing a lightweight version.

**Comment by Maks3w** [comment]
@akrabat :+1:

**Pull request closed without merging**
