### PR TITLE
Remove the submodule option as the ZF2 repository is now a meta package

### PR DESCRIPTION
**Pull request by akrabat**

### CODE REVIEW

**Comment by Ocramius** [comment]
Please someone tell me that I can press the green button without starting a giant s***storm

**Comment by jeremiahsmall** [comment]
:+1: for dumping submodules
:+1: for ignoring `vendor`

**Comment by Maks3w** [comment]
@Ocramius :+1:

**Comment by Ocramius** [comment]
\o/

**Pull request merged**
